spring:
  datasource:
    url: ${DB_PATH:jdbc:postgresql://10.68.17.119:5432/core_crm_db?currentSchema=public}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:mypassword}

  liquibase:
    change-log: liquibase/changelog-master.yml