spring:
  datasource:
    url: ${DB_PATH:jdbc:postgresql://localhost:5432/core_crm_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root123}

  liquibase:
    change-log: liquibase/changelog-master.yml